### ISSUE TITLE
Copy action from share sheet should copy actual image file to clipboard

### ISSUE THREAD

**Issue by erin-dot-io** [thoughtbot/poppins#51]
- Tap on an image
- Pick "Copy" action
- Go to another app like GroupMe or Messages
- Paste from clipboard

Result: Pastes a dropbox link to the gif

Expected: Pastes the actual gif

**Comment by tonyd256** [comment]
Thanks for opening this @erindotio. I think copying the link is still important. I would vote for the native copy action to copy the GIF like you say and at the same time introduce a custom copy action that allows the user to copy the GIF link.
