### ISSUE TITLE
Image should show up when shared to apps like GroupMe

### ISSUE THREAD

**Issue by erin-dot-io** [thoughtbot/poppins#52]
- Tap on an image
- Choose to share directly to an app like GroupMe
- Post the image (with optional text)
- Go to the app just posted to to view the post

Result: Image wasn't posted. Just the optional text.

Expected: Image and text we're posted.

Notes: Maybe it's a problem specific to GroupMe's handling of incoming share sheet posts?

**Comment by tonyd256** [comment]
Interesting. I haven't tried this with GroupMe yet. I'll have to try this out and get back to you.
