### ISSUE TITLE
Module file was created by an older version of compiler; rebuild 'Cascade' and try again

### ISSUE THREAD

**Issue by NirmitDagly** [thoughtbot/poppins#54]
Hello,
I am trying to run poppins-master source  code reference. I have updated carthage with all the available frameworks required for project. I am using XCode 7.3.

I am getting the error in code as follow:-
"Module file was created by an older version of compiler; rebuild 'Cascade' and try again".

By doing google, I came to know about this solutions:-
1. update carthage without use of binaries command
2. delete derived data of the project and then update carthage of the project

I have tried both of this solution many times but unable to remove the error. Please help me to solve this issue asap.

**Comment by gfontenot** [comment]
Did you use `carthage bootstrap --no-use-binaries`?

**Comment by gfontenot** [comment]
fwiw, neither this project nor Cascade have been updated in a _long_ time, so they almost certainly won't compile with Xcode 7.3/Swift 2.3 without source changes.

**Comment by NirmitDagly** [comment]
Yes.. I have used carthage bootstrap --no-use-binaries but It was no luck! I am still getting the same error.

What changes need to be done in the source code? Please let me know. If I am able to do that I'll make that changes and try to make this source code to compile with latest XCode 7.x and Swift 2.3 or Swift 3.0.
